server:
    servlet:
        context-path: /unility
    port: 8080

spring:
    profiles:
        active: local
        include: auth

    jackson:
        property-naming-strategy: LOWER_CAMEL_CASE

    servlet:
        multipart:
            enabled: true
            file-size-threshold: 2KB
            max-file-size: 200MB
            max-request-size: 215MB